# Generated by Django 4.1.4 on 2023-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicsSalaryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicsSalaryByYearsForProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicsVacanciesByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy', models.TextField(verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicsVacanciesByYearForProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('vacancy', models.TextField(verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='FractionVacanciesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Город')),
                ('fraction', models.FloatField(verbose_name='Доля')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryLevelsByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(verbose_name='Город')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='TopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('count', models.IntegerField(verbose_name='Количество повторений')),
            ],
        ),
    ]
